services:
  postgres:
    image: postgres:15
    container_name: solar_db
    environment:
      POSTGRES_DB: solar_financing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: solar_financing,airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:3.0.0
    container_name: solar_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:${DB_PASSWORD}@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'solar123'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      DB_HOST: postgres
      DB_PORT: 5432
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "pip install 'yfinance==0.2.18' 'multitasking==0.0.11' pandas psycopg2-binary sqlalchemy python-dotenv &&
               airflow db migrate &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
               airflow webserver & airflow scheduler"
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
    container_name: solar_dashboard
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  airflow_logs:
